typography_spectrum: 0.79852
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5625
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.86639
analytics:
  google: null
  facebook: null
  twitter: null
name: Epic Rance
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Epic Rants
purpose: []
