name: Epic Rance
favicon: null
layout_spectrum: 0.4542072454933077
typography_spectrum: 0.79852
title: Epic Rance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5631976884324104
  lightness: 0.2500898076687008
  saturation: 0.8011545173358172
  rhythmicContrast: 0.4372824728488922
purpose: []
